shell = "/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
decorations = "Buttonless"
#opacity = 0.8
#blur = false
startup_mode = "Maximized"

[font]
normal.family = "Hack Nerd Font Mono"
size = 22

[colors.primary]
#cursor.cursor = "#40BDFF"
background = "#181818"

[cursor]
vi_mode_style.shape = "BLOCK"

[mouse]
hide_when_typing = true

# https://www.joshmedeski.com/posts/macos-keyboard-shortcuts-for-tmux/
[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u0002\u0031"  # Ctrl-b 1

[[keyboard.bindings]]
key = "2"
mods = "Command"
chars = "\u0002\u0032"  # Ctrl-b 2

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u0002\u0033"  # Ctrl-b 3

[[keyboard.bindings]]
key = "4"
mods = "Command"
chars = "\u0002\u0034"  # Ctrl-b 4

[[keyboard.bindings]]
key = "5"
mods = "Command"
chars = "\u0002\u0035"  # Ctrl-b 5

[[keyboard.bindings]]
key = "6"
mods = "Command"
chars = "\u0002\u0036"  # Ctrl-b 6

[[keyboard.bindings]]
key = "7"
mods = "Command"
chars = "\u0002\u0037"  # Ctrl-b 7

[[keyboard.bindings]]
key = "8"
mods = "Command"
chars = "\u0002\u0038"  # Ctrl-b 8

[[keyboard.bindings]]
key = "9"
mods = "Command"
chars = "\u0002\u0039"  # Ctrl-b 9
