shell = "/opt/homebrew/bin/bash"

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
decorations = "Buttonless"
#opacity = 0.8
#blur = false
startup_mode = "Maximized"

[font]
normal.family = "Hack Nerd Font Mono"
size = 22

[colors]
#cursor.cursor = "#40BDFF"

[cursor]
vi_mode_style.shape = "BLOCK"

[mouse]
hide_when_typing = true
