let mapleader = ' '
set nocompatible
set shiftwidth=4
set softtabstop=4
set expandtab
set cindent

inoremap jk <Esc>

syntax enable
set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme solarized

set noswapfile
set colorcolumn=80
set scrolloff=8
filetype indent on
set wrap
set showmatch
set number
set laststatus=2
set ignorecase
set smartcase

map <S-l> :bnext<cr>
map <S-h> :bprev<cr>
map <Leader>d :bdelete<cr>
